version: '3.8'

services:

  backend:
    container_name: "Backend"
    build: ./services/backend
    image: stupidwolfy/hydroponic-backend
    ports:
      - 5000:5000
    volumes:
      - ./services/backend:/app
    environment:
      HOST_HOSTNAME: ${HOST_HOSTNAME:-pi-project}
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 5000
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
    privileged: true
    restart: unless-stopped


  frontend:
    container_name: "Frontend"
    build: ./services/frontend
    image: stupidwolfy/hydroponic-frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080
    restart: unless-stopped
